baseURL = "https://rom-9611.github.io/rom_archrive/"
languageCode = "en"
title = "ROM Archive"
theme = "stack"

[outputs]
home = ["HTML", "RSS", "JSON"]

[params]
homeInfoParams = false
ShowReadingTime = true
ShowPostNavLinks = true
# Enable search
enableSearch = true
ShowToc = true
ShowCodeCopyButtons = true

[module]
 [[module.imports]]
  path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

