baseURL = "https://rom-9611.github.io/rom_archrive/"
languageCode = "en"
title = "ROM Archive"

[module]
  [[module.imports]]
    path = "github.com/CaiJimmy/hugo-theme-stack/v4"

[outputs]
home = ["HTML", "RSS", "JSON"]

[pagination]
pagerSize = 10

[taxonomies]
tag = "tags"
category = "categories"

[params]
  mainSections = ["posts"]

  [params.sidebar]
    emoji = "ðŸ“±"
    subtitle = "Android â€¢ Root â€¢ Arch â€¢ ROMs"

  [params.article]
    readingTime = true
    toc = true

  [params.search]
    enable = true



