baseURL = "https://rom-9611.github.io/rom_archrive/"
languageCode = "en"
title = "ROM Archive"
theme = "PaperMod"

[outputs]
home = ["HTML", "RSS", "JSON"]

[taxonomies]
tag = "tags"
category = "categories"

##disableKinds = []



[params]
homeInfoParams = false
ShowReadingTime = true
ShowPostNavLinks = true
# Enable search
enableSearch = true
ShowToc = true
ShowCodeCopyButtons = true


[params.fuseOpts]
isCaseSensitive = false
shouldSort = true
location = 0
distance = 1000
threshold = 0.4
minMatchCharLength = 2
keys = ["title", "permalink", "summary", "content"]

